trigger: none
pool: dev-infra-pool
jobs:
  - job: terraforminit
    steps: 
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: terraforminit
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/rg'
        backendServiceArm: 'kashi-dev-app'
        backendAzureRmResourceGroupName: 'artifact_rg'
        backendAzureRmStorageAccountName: 'artifactstg'
        backendAzureRmContainerName: 'artifactcont'
        backendAzureRmKey: 'terraform.tfstate'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/rg'
        artifact: 'tfsec_artifact'
        publishLocation: 'pipeline'

  - job: terraformplan
    dependsOn: terraforminit
    steps: 
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'tfsec_artifact'
        targetPath: '$(Pipeline.Workspace)'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          cd $(Pipeline.Workspace)/rg
          chmod -R +x rg

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/rg'
        environmentServiceNameAzureRM: 'kashi-dev-app'